#Implementation
#DB name = PHPproject

#DROP SCHEMA IF EXISTS
DROP TABLE IF EXISTS Basket;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Users; 

CREATE TABLE Users(
Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Username VARCHAR(50) NOT NULL,
Password VARCHAR(50) NOT NULL
)
ENGINE=InnoDB; 

CREATE TABLE Products(
Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
ProductName VARCHAR(50),
ProductPrice INT
#image?
)
ENGINE=InnoDB;

CREATE TABLE Basket(
Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
UserId INT NOT NULL,
ProductId INT NOT NULL,
CONSTRAINT FK_User FOREIGN KEY(UserId) REFERENCES Users(Id),
CONSTRAINT FK_Product FOREIGN KEY(ProductId) REFERENCES Products(Id)
)
ENGINE=InnoDB;